algoritmo "Contar até onde o usuário quiser."
// Função : Ele vai pedir um número e vai contar até onde o usuário quiser.
// Autor : Soryu Yamato.
// Data : 9/12/2020
var

   contador,valor:Inteiro
inicio

      Escreva("Quer contar até quando? ")
      Leia(valor)
      contador <- 0
      Enquanto (contador<=valor) faca
          Escreval("Estou no número ",contador)
          contador <- contador + 1
      FimEnquanto
      Escreval("Terminei de contar")
      
fimalgoritmo
