algoritmo "Melhor aluno da turma"
// Função : Verificar quem é o melhor aluno da turma.
// Autor : Soryu Yamato.
// Data : 9/13/2020
var

   quantidadeDeAlunosSalaDeAula:Inteiro
inicio

      Escreval("--------------------------")
      Escreval("  ESCOLA SANTA PACIÊNCIA  ")
      Escreval("--------------------------")
      Escreva("Quantos aluno a turma tem? ")
      Leia(quantidadeDeAlunosSalaDeAula)
      
fimalgoritmo
