algoritmo "Somar dois valores"
// Função : Ele vai usar a função para somar dois valores.
// Autor : Soryu Yamato.
// Data : 9/16/2020
var

   valor1,valor2,soma:Inteiro
Funcao somar(x,y:Inteiro):Inteiro
Inicio
      Retorne(x+y)
FimFuncao
inicio

      Escreva("Digite o 1° valor: ")
      Leia(valor1)
      Escreva("Digite o 2° valor: ")
      Leia(valor2)
      soma <- somar(valor1,valor2)
      Escreval("A soma entre ",valor1," e ",valor2," é = : ",soma)
      
fimalgoritmo
