algoritmo "Creuza 01"
// Função : Creuza vai fazer aniversário e temos que ajudar a ela descobrir quantos anos vai fazer.
// Autor : Soryu Yamato.
// Data : 9/11/2020
var

   anoAtual,anoNascimento,idade:Inteiro
   
inicio

      Escreva("Em que ano estamos? ")
      Leia(anoAtual)
      Escreva("Em que ano nasci? ")
      Leia(anoNascimento)
      idade <- anoAtual - anoNascimento
      Escreval("Minha idade será ",idade," anos")
      
fimalgoritmo
