algoritmo "Soma entre dois números"
// Função : Solicitar dois números para o usuário mostrar a soma entre eles.
// Autor : Soryu Yamato.
// Data : 9/11/2020
var

   numero1,numero2,soma:Inteiro
   
inicio

      Escreva("Digite um número: ")
      Leia(numero1)
      Escreva("Digite outro número: ")
      Leia(numero2)
      soma <- numero1+numero2
      Escreval("A soma entre ",numero1," e",numero2," é: ",soma)
      
fimalgoritmo
