algoritmo "Média de dois números"
// Função : Pegar dois números e fazer sua média.
// Autor : Soryu Yamato.
// Data : 9/11/2020
var

   numero1,numero2,media:real
   
inicio

      Escreva("Digite um número ")
      Leia(numero1)
      Escreva("Digite outro número ")
      Leia(numero2)
      media <- (numero1+numero2) / 2
      Escreval("A média entre os números ",numero1," e ",numero2," é ",media)
      
fimalgoritmo
